"""Generate dnsmasq.conf from current settings (proxyDHCP or full DHCP).

render() only writes the config file. In Beacon, a sidecar container watching
the shared volume restarted dnsmasq whenever this changed. Lantern's DHCP/TFTP
service runs on the host instead (see docs/design.md's "DHCP/TFTP" section),
and the mechanism for a rootless container to trigger a host-level reload
without holding host root itself hasn't been designed yet — trigger_reload()
below is the stub for that, called nowhere yet. Until it exists, applying a
config change needs a manual reload on the host.
"""
import logging

from sqlalchemy.orm import Session

from .. import config
from ..store import all_settings

log = logging.getLogger("lantern.dnsmasq")

HEADER = """# GENERATED by the Lantern web app. Do not edit by hand.
port=0
log-dhcp
# Log DHCP/PXE activity to a file the web app reads for the dashboard's
# recent-clients view (works in proxyDHCP, which has no lease file).
log-facility=/dnsmasq/dnsmasq.log
"""

ARCH_DETECT = """
# --- Architecture detection (BIOS vs UEFI) ---
dhcp-match=set:efi32,option:client-arch,6
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efibc,option:client-arch,9

# iPXE identifies itself (so we serve the binary to raw firmware, but the HTTP
# menu to iPXE) via user-class and the encapsulated iPXE option (175).
dhcp-userclass=set:ipxe,iPXE
dhcp-match=set:ipxe,175
"""


def _tftp_block() -> str:
    """Serve the iPXE binaries over TFTP.

    Deliberately independent of the DHCP service: with an external DHCP server
    driving the boot (next-server/filename set there), TFTP is the only thing
    this box needs to provide, so disabling DHCP must not disable TFTP too.
    """
    return (
        "# --- TFTP: serves the iPXE binaries ---\n"
        "enable-tftp\n"
        "tftp-root=/tftp"
    )


def _boot_block(server_ip: str, tftp_enabled: bool) -> str:
    """Firmware -> iPXE handoff. Only meaningful when we answer DHCP.

    Uses pxe-service (not dhcp-boot) for the binary handoff because that is the
    mechanism dnsmasq honours in proxyDHCP mode: raw firmware is chainloaded the
    arch-correct iPXE binary, while iPXE itself is sent the HTTP menu.
    """
    menu_host = server_ip or "127.0.0.1"
    lines = []
    if tftp_enabled:
        lines += [
            "# Raw firmware (not yet iPXE): chainload the matching iPXE binary.",
            "pxe-prompt=\"Loading iPXE...\",1",
            "pxe-service=tag:!ipxe,x86PC,\"iPXE (BIOS)\",undionly.kpxe",
            "pxe-service=tag:!ipxe,X86-64_EFI,\"iPXE (UEFI)\",ipxe.efi",
            "pxe-service=tag:!ipxe,BC_EFI,\"iPXE (UEFI)\",ipxe.efi",
            "",
        ]
    # Once iPXE is running, chain it to the single HTTP menu. The embedded
    # script prefers this URL over ${next-server} (see the dnsmasq image build):
    # in proxyDHCP the client's own DHCP server owns next-server, and routers
    # commonly point it at themselves.
    lines.append("# iPXE clients: load the HTTP boot menu.")
    lines.append(f"dhcp-boot=tag:ipxe,http://{menu_host}/boot.ipxe")
    return "\n".join(lines)


def build_config(settings: dict) -> str:
    server_ip = settings.get("server_ip", "")
    iface = settings.get("boot_interface", "eth0")
    dhcp_on = settings.get("svc_dhcp", "1") == "1"
    tftp_on = settings.get("svc_tftp", "1") == "1"
    mode = settings.get("dhcp_mode", "proxy")

    parts = [HEADER]
    if iface:
        parts.append(f"interface={iface}")
        # Bind ONLY the chosen interface so DHCP never leaks onto other NICs
        # (e.g. a production LAN that already has a DHCP server).
        parts.append("bind-interfaces")
        parts.append("except-interface=lo")
    parts.append(ARCH_DETECT)

    if tftp_on:
        parts.append(_tftp_block())

    # External DHCP: the admin's own DHCP server hands out next-server/filename,
    # so we must not answer DHCP at all -- not even as a proxy, which would race
    # the very server that is already doing the job. TFTP above is the whole
    # contribution. Deliberately independent of svc_dhcp: picking this mode IS
    # the statement that something else owns DHCP.
    if mode == "external":
        parts.append(
            "# --- External DHCP: your own DHCP server drives the boot ---\n"
            "# This box answers no DHCP whatsoever; it only serves the iPXE\n"
            "# binaries over TFTP. Point your DHCP server at:\n"
            f"#     next-server = {server_ip or '<this server IP>'}\n"
            "#     filename    = ipxe.efi        (UEFI clients)\n"
            "#     filename    = undionly.kpxe   (legacy BIOS clients)"
        )
    elif dhcp_on:
        if mode == "full":
            parts.append(
                "# --- Full DHCP: this server assigns IP addresses ---\n"
                f"dhcp-range={settings.get('dhcp_range_start')},"
                f"{settings.get('dhcp_range_end')},"
                f"{settings.get('dhcp_subnet_mask')},12h\n"
                f"dhcp-option=option:router,{settings.get('dhcp_gateway')}\n"
                f"dhcp-option=option:dns-server,{settings.get('dhcp_dns')}"
            )
        else:
            # proxyDHCP: answer only PXE, leave addressing to the existing server.
            net = server_ip or "0.0.0.0"
            parts.append(
                "# --- proxyDHCP: runs beside your existing DHCP server ---\n"
                f"dhcp-range={net},proxy"
            )
        parts.append(_boot_block(server_ip, tftp_on))
    else:
        parts.append(
            "# DHCP service disabled in Server Settings. TFTP above (if enabled)\n"
            "# still serves the iPXE binaries, so an external DHCP server can\n"
            "# boot clients by pointing next-server/filename at this box."
        )

    return "\n".join(parts) + "\n"


def render(db: Session) -> str:
    settings = all_settings(db)
    text = build_config(settings)
    out = config.DNSMASQ_DIR / "dnsmasq.conf"
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    return text


def trigger_reload() -> bool:
    """Ask the host DHCP/TFTP service to reload the config render() just wrote.

    Not implemented — see the module docstring and docs/design.md's "DHCP/TFTP"
    section, which calls out that this needs its own scoped-privilege design
    (a sudoers rule or a systemd socket-activated unit) before it can be built.
    Returns False (nothing was reloaded) so callers can tell the admin.
    """
    return False
