"""Generate dnsmasq.conf from current settings (proxyDHCP or full DHCP).

render() writes the config into DNSMASQ_DIR, and that write is the whole
interface to the DHCP/TFTP service. dnsmasq runs on the host, not in a container
(see docs/design.md's "DHCP/TFTP" section), and a systemd path unit there
(host/systemd/lantern-apply.path) notices the change and runs
`lantern-host apply`. That checks every directive against an allowlist, installs
the config and restarts dnsmasq, then writes the result to apply-status.json,
which apply_status() reads for the UI. The container never gets anything on the
host it can call.

Any directive added here must also be added to ALLOWED_DIRECTIVES in
host/lantern_host.py, or the host will refuse the config. Directives that name a
file or run a program (log-facility, tftp-root, dhcp-script, ...) are owned by
the host and must not be emitted here.
"""
import json
import logging
import os

from sqlalchemy.orm import Session

from .. import config
from ..store import all_settings

log = logging.getLogger("lantern.dnsmasq")

HEADER = """# GENERATED by the Lantern web app. Do not edit by hand.
port=0
# DHCP/PXE activity goes to the host's journal, which the host copies to
# DNSMASQ_DIR/dnsmasq.log for the dashboard's recent-clients view (works in
# proxyDHCP, which has no lease file).
log-dhcp
"""

ARCH_DETECT = """
# --- Architecture detection (BIOS vs UEFI) ---
dhcp-match=set:efi32,option:client-arch,6
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efibc,option:client-arch,9

# iPXE identifies itself (so we serve the binary to raw firmware, but the HTTP
# menu to iPXE) via user-class and the encapsulated iPXE option (175).
dhcp-userclass=set:ipxe,iPXE
dhcp-match=set:ipxe,175
"""


def _tftp_block() -> str:
    """Serve the iPXE binaries over TFTP.

    Deliberately independent of the DHCP service: with an external DHCP server
    driving the boot (next-server/filename set there), TFTP is the only thing
    this box needs to provide, so disabling DHCP must not disable TFTP too.
    The TFTP root is set by the host, which copies the binaries staged in
    TFTP_DIR into it.
    """
    return (
        "# --- TFTP: serves the iPXE binaries ---\n"
        "enable-tftp"
    )


def _boot_block(server_ip: str, tftp_enabled: bool) -> str:
    """Firmware -> iPXE handoff. Only meaningful when we answer DHCP.

    Uses pxe-service (not dhcp-boot) for the binary handoff because that is the
    mechanism dnsmasq honours in proxyDHCP mode: raw firmware is chainloaded the
    arch-correct iPXE binary, while iPXE itself is sent the HTTP menu.
    """
    menu_host = server_ip or "127.0.0.1"
    lines = []
    if tftp_enabled:
        lines += [
            "# Raw firmware (not yet iPXE): chainload the matching iPXE binary.",
            "pxe-prompt=\"Loading iPXE...\",1",
            "pxe-service=tag:!ipxe,x86PC,\"iPXE (BIOS)\",undionly.kpxe",
            "pxe-service=tag:!ipxe,X86-64_EFI,\"iPXE (UEFI)\",ipxe.efi",
            "pxe-service=tag:!ipxe,BC_EFI,\"iPXE (UEFI)\",ipxe.efi",
            "",
        ]
    # Once iPXE is running, chain it to the single HTTP menu. The embedded
    # script prefers this URL over ${next-server} (see the dnsmasq image build):
    # in proxyDHCP the client's own DHCP server owns next-server, and routers
    # commonly point it at themselves.
    lines.append("# iPXE clients: load the HTTP boot menu.")
    lines.append(f"dhcp-boot=tag:ipxe,http://{menu_host}/boot.ipxe")
    return "\n".join(lines)


def build_config(settings: dict) -> str:
    server_ip = settings.get("server_ip", "")
    iface = settings.get("boot_interface", "eth0")
    dhcp_on = settings.get("svc_dhcp", "1") == "1"
    tftp_on = settings.get("svc_tftp", "1") == "1"
    mode = settings.get("dhcp_mode", "proxy")

    parts = [HEADER]
    if iface:
        parts.append(f"interface={iface}")
        # Bind ONLY the chosen interface so DHCP never leaks onto other NICs
        # (e.g. a production LAN that already has a DHCP server).
        parts.append("bind-interfaces")
        parts.append("except-interface=lo")
    parts.append(ARCH_DETECT)

    if tftp_on:
        parts.append(_tftp_block())

    # External DHCP: the admin's own DHCP server hands out next-server/filename,
    # so we must not answer DHCP at all -- not even as a proxy, which would race
    # the very server that is already doing the job. TFTP above is the whole
    # contribution. Deliberately independent of svc_dhcp: picking this mode IS
    # the statement that something else owns DHCP.
    if mode == "external":
        parts.append(
            "# --- External DHCP: your own DHCP server drives the boot ---\n"
            "# This box answers no DHCP whatsoever; it only serves the iPXE\n"
            "# binaries over TFTP. Point your DHCP server at:\n"
            f"#     next-server = {server_ip or '<this server IP>'}\n"
            "#     filename    = ipxe.efi        (UEFI clients)\n"
            "#     filename    = undionly.kpxe   (legacy BIOS clients)"
        )
    elif dhcp_on:
        if mode == "full":
            parts.append(
                "# --- Full DHCP: this server assigns IP addresses ---\n"
                f"dhcp-range={settings.get('dhcp_range_start')},"
                f"{settings.get('dhcp_range_end')},"
                f"{settings.get('dhcp_subnet_mask')},12h\n"
                f"dhcp-option=option:router,{settings.get('dhcp_gateway')}\n"
                f"dhcp-option=option:dns-server,{settings.get('dhcp_dns')}"
            )
        else:
            # proxyDHCP: answer only PXE, leave addressing to the existing server.
            net = server_ip or "0.0.0.0"
            parts.append(
                "# --- proxyDHCP: runs beside your existing DHCP server ---\n"
                f"dhcp-range={net},proxy"
            )
        parts.append(_boot_block(server_ip, tftp_on))
    else:
        parts.append(
            "# DHCP service disabled in Server Settings. TFTP above (if enabled)\n"
            "# still serves the iPXE binaries, so an external DHCP server can\n"
            "# boot clients by pointing next-server/filename at this box."
        )

    return "\n".join(parts) + "\n"


def render(db: Session) -> str:
    settings = all_settings(db)
    text = build_config(settings)
    out = config.DNSMASQ_DIR / "dnsmasq.conf"
    if not out.exists() or out.read_text() != text:
        # Written to a temp file and renamed so the host's path unit never picks
        # up a half-written config.
        tmp = out.with_name(".dnsmasq.conf.tmp")
        tmp.write_text(text)
        os.replace(tmp, out)
    return text


def apply_status() -> dict | None:
    """The host's result for the last config it applied, or None if it hasn't
    run yet (e.g. host/install.sh hasn't been run on this machine).

    Keys: ok (bool), message (str), applied_at (ISO 8601 UTC), restarted (bool).
    """
    try:
        data = json.loads((config.DNSMASQ_DIR / "apply-status.json").read_text())
    except (OSError, ValueError):
        return None
    if not isinstance(data, dict):
        return None
    return {
        "ok": data.get("ok") is True,
        "message": str(data.get("message", "")),
        "applied_at": str(data.get("applied_at", "")),
        "restarted": data.get("restarted") is True,
    }
