"""Generate the single boot.ipxe menu served to both BIOS and UEFI clients.

The menu uses iPXE's default plain black-and-white text rendering — no colour
scheme or background is applied.  The iPXE binaries are built without
CONSOLE_FRAMEBUFFER so the menu runs in plain VGA text mode, where the arrow
keys decode correctly for navigating the choices.
"""
import logging

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .. import config
from ..models import Image
from ..store import all_settings

log = logging.getLogger("lantern.ipxe")


def _header(server_ip: str, title: str) -> str:
    host = server_ip or "${next-server}"
    host_url = f"http://{host}"
    return f"""#!ipxe
# GENERATED by the Lantern web app. Do not edit by hand.

set boot-url {host_url}
# Used by NFS-netboot images: kernel cmdline references ${{server-ip}} for nfsroot.
set server-ip {host}
set menu-title {title}
"""


MENU_TOP = """
:start
menu ${menu-title}
item --gap -- ----------------------- Operating Systems -----------------------
"""

_MENU_FOOTER_TIMEOUT = """item --gap -- ----------------------------------------------------------------
item shell        iPXE shell
item reboot       Reboot
item exit_ipxe    Continue local boot
choose --default {default} --timeout {timeout_ms} target && goto ${target}

:shell
echo Type 'exit' to return to the menu.
shell
goto start

:reboot
reboot

:exit_ipxe
exit
"""

_MENU_FOOTER_NO_TIMEOUT = """item --gap -- ----------------------------------------------------------------
item shell        iPXE shell
item reboot       Reboot
item exit_ipxe    Continue local boot
choose --default {default} target && goto ${target}

:shell
echo Type 'exit' to return to the menu.
shell
goto start

:reboot
reboot

:exit_ipxe
exit
"""


def _track(tag: str, img: Image, base_url: str) -> str:
    """Best-effort ping so the dashboard can count this deployment.

    Fetched and immediately freed: it records a BootEvent server-side, we don't
    use the response. `||` makes it non-fatal -- if it fails the client still
    boots from the HTTP boot root, which serves the files below independently.

    base_url is the HTTP boot root; it reverse-proxies /track/ to the web app
    so the menu reaches tracking over the same single boot-url the client
    already uses for everything else.
    """
    url = f"{base_url}/track/{img.id}?mac=${{net0/mac}}&ip=${{net0/ip}}"
    return (f"imgfetch --name track {url} || goto {tag}_boot\n"
            f"imgfree track || goto {tag}_boot\n"
            f":{tag}_boot\n")


def _xcpng_label(tag: str, img: Image, base_url: str, args: str) -> str:
    """Chainload the per-image standalone GRUB, which multiboots Xen.

    iPXE cannot multiboot under UEFI (IMAGE_MULTIBOOT is BIOS-only), which is the
    arch most XCP-NG hosts boot. So we hand off to a grub.efi built at extraction
    time (services.images._build_xcpng_grub); GRUB fetches xen/vmlinuz/install.img
    over HTTP and does the multiboot2 itself.
    """
    # bootx64.efi sits in the same extracted dir as vmlinuz (os/<id>/).
    img_dir = img.initrd_path.rsplit("/", 1)[0]
    grub = f"{base_url}/{img_dir}/bootx64.efi"
    return (
        f":{tag}\n"
        + _track(tag, img, base_url)
        + f"echo Booting {img.name} (XCP-NG via GRUB) ...\n"
        f"chain {grub} || goto start\n"
    )


def _windows_label(tag: str, img: Image, base_url: str) -> str:
    """Boot Windows via wimboot; WinPE reaches the install media over SMB.

    wimboot loads bootmgr + BCD + boot.sdi + boot.wim into a ramdisk and starts
    WinPE. The full install media (sources/install.wim and friends) isn't in
    boot.wim — under UEFI iPXE can't sanhook the ISO as a CD, so instead the
    boot.wim's winpeshl.ini (patched at extraction time to run lantern-setup.cmd)
    mounts the SMB share and runs setup.exe from it.

    The trailing filename on each initrd line names the ramdisk file so
    bootmgr/BCD resolve them by their expected names.
    """
    img_dir = img.kernel_path.rsplit("/", 1)[0]  # os/<id>
    return (
        f":{tag}\n"
        + _track(tag, img, base_url)
        + f"echo Booting {img.name} (Windows) ...\n"
        f"kernel {base_url}/wimboot || goto start\n"
        f"initrd {base_url}/{img_dir}/bootmgr   bootmgr  || goto start\n"
        f"initrd {base_url}/{img_dir}/bcd       BCD      || goto start\n"
        f"initrd {base_url}/{img_dir}/boot.sdi  boot.sdi || goto start\n"
        f"initrd {base_url}/{img_dir}/boot.wim  boot.wim || goto start\n"
        f"boot || goto start\n"
    )


def _image_entries(images: list[Image]) -> tuple[str, str]:
    """Return (menu items, boot labels) for ready, enabled images."""
    items = []
    labels = []
    for img in images:
        tag = f"os_{img.id}"
        star = " ★" if img.is_default else ""
        items.append(f"item {tag}        {img.name}{star}")
        base_url = "${boot-url}"
        args = img.boot_args or ""
        if img.os_family == "xcpng":
            labels.append(_xcpng_label(tag, img, base_url, args))
            continue
        if img.os_family == "windows":
            labels.append(_windows_label(tag, img, base_url))
            continue
        kernel = f"{base_url}/{img.kernel_path}"
        initrd = f"{base_url}/{img.initrd_path}"
        labels.append(
            f":{tag}\n"
            + _track(tag, img, base_url)
            + f"echo Booting {img.name} ...\n"
            f"kernel {kernel} {args} || goto start\n"
            f"initrd {initrd} || goto start\n"
            f"boot || goto start\n"
        )
    return "\n".join(items), "\n".join(labels)


def render(db: Session) -> str:
    settings = all_settings(db)
    server_ip = settings.get("server_ip", "")
    title = settings.get("menu_title", "Lantern")

    # Sort by explicit display_order (NULLs last), then alphabetically.
    images = db.execute(
        select(Image).where(Image.status == "ready", Image.enabled == 1)
        .order_by(Image.display_order.is_(None), Image.display_order,
                  func.lower(Image.name))
    ).scalars().all()

    items, labels = _image_entries(images)
    if not items:
        items = "item --gap -- (no images uploaded yet — add one in the web UI)"

    # Highlighting and auto-booting are separate decisions.
    #
    # Highlight: an explicitly marked image if there is one, else the first entry
    # in menu order, so the selection starts on an OS rather than on "Continue
    # local boot". This only positions the cursor -- it boots nothing.
    #
    # Countdown: ONLY for an explicitly marked image. With nothing marked the
    # menu waits for a human indefinitely. Never pick a boot target on the
    # admin's behalf.
    default_img = next((img for img in images if img.is_default), None)
    highlight = default_img or (images[0] if images else None)
    default = f"os_{highlight.id}" if highlight else "exit_ipxe"

    timeout_secs = 0
    if default_img:
        try:
            timeout_secs = max(0, int(settings.get("boot_timeout", "30")))
        except ValueError:
            timeout_secs = 30

    if timeout_secs > 0:
        footer = _MENU_FOOTER_TIMEOUT.replace(
            "{default}", default).replace(
            "{timeout_ms}", str(timeout_secs * 1000))
    else:
        footer = _MENU_FOOTER_NO_TIMEOUT.replace("{default}", default)

    text = (
        _header(server_ip, title)
        + MENU_TOP
        + items + "\n"
        + footer
        + "\n"
        + labels
    )

    out = config.BOOTROOT_DIR / "boot.ipxe"
    out.write_text(text)

    return text
